book_repo: greenplum-db/gpdb-docs/book

public_host: localhost:9292

sections:
- repository:
    name: markdown
    at_path: common
  directory: 7-0/common
  subnav_template: gpdb-landing-subnav

- repository:
    name: markdown
    at_path: pxf
  directory: 7-0/pxf
  subnav_template: pxf-subnav

- repository:
    name: markdown
    at_path: cloud
  directory: 7-0/cloud
  subnav_template: cloud-subnav

- repository:
    name: markdown
    at_path: install_guide
  directory: 7-0/install_guide
  subnav_template: install-subnav

- repository:
    name: markdown
    at_path: best_practices
  directory: 7-0/best_practices
  subnav_template: bp-subnav

- repository:
    name: markdown
    at_path: admin_guide
  directory: 7-0/admin_guide
  subnav_template: admin-subnav

- repository:
    name: markdown
    at_path: analytics
  directory: 7-0/analytics
  subnav_template: analytics-subnav
  
- repository:
    name: markdown
    at_path: security-guide
  directory: 7-0/security-guide
  subnav_template: security-subnav

- repository:
    name: markdown
    at_path: utility_guide
  directory: 7-0/utility_guide
  subnav_template: utility-subnav

- repository:
    name: markdown
    at_path: ref_guide
  directory: 7-0/ref_guide
  subnav_template: reference-subnav

template_variables:
  book_title: Greenplum Database Documentation
  book_title_short:  Greenplum Database Docs
  domain_name: greenplum.org
  product_link: <div class="header-item"><a href="https://greenplum.org">Back to Greenplum Database</a></div>
  product_url: https://greenplum.org
  support_call_to_action: <a href="https://greenplum.org/community/" target="_blank">Need Support?</a>
  support_link: <a href="https://github.com/greenplum-db/gpdb/wiki">Wiki</a>
  support_url: https://greenplum.org

broken_link_exclusions: iefix|arrowhead|overview_pxf.html|pxf.html|pxf-cluster.html|pxf_kerbhdfs.html|cfginitstart_pxf.html|init_pxf.html|access_hdfs.html|intro_pxf.html|using_pxf.html|client_instcfg.html|install_java.html|pxfuserimpers.html|jdbc_cfg.html|gpcopy|client_tool_guides|postGIS
