platform: linux
image_resource:
  type: registry-image
inputs:
  - name: gpdb_src
  - name: llvm-with-asserts-packages
    optional: true
outputs:
  - name: gpdb_artifacts
run:
  path: gpdb_src/concourse/scripts/compile_gpdb.bash
caches:
  - path: ccache_dir
params:
  BLD_TARGETS:
  OUTPUT_ARTIFACT_DIR: gpdb_artifacts
  CONFIGURE_FLAGS:
  RC_BUILD_TYPE_GCS:
  USE_CCACHE:
  SKIP_UNITTESTS:
  GPDB_BIN_FILENAME:
