platform: linux
image_resource:
  type: registry-image
inputs:
  - name: gpdb_src
  - name: filedump_src
  - name: bin_gpdb
  - name: llvm-with-asserts-packages
    optional: true
outputs:
  - name: sqldump
run:
 path: gpdb_src/concourse/scripts/filedump_gpdb.bash
params:
  DUMP_DB: "false"
  MAKE_TEST_COMMAND: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_OS: ""
  CONFIGURE_FLAGS: ""
  WITH_MIRRORS:
