platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb7-rocky8-test
inputs:
  - name: gpdb_src
  - name: explain_output
  - name: explain_output_baseline
outputs:
  - name: diffs
params:
  prefix:
run:
  path: gpdb_src/concourse/scripts/diff_explain_results_with_baseline.bash
