---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/ccp
    tag: latest

inputs:
- name: terraform
- name: ccp_src
- name: cluster_env_files
- name: gpdb_src
- name: bin_gpdb
- name: sqldump

run:
  path: gpdb_src/concourse/scripts/test_upgrade.bash
  args: [ '-c', '-t', 'bin_gpdb', '-s', 'sqldump/dump.sql.xz' ]

params:
  DEBUG_UPGRADE: ""
  NUMBER_OF_NODES: 2
